-- Sistema OnBus - Database

CREATE DATABASE IF NOT EXISTS onbus_local;
USE onbus_local;

CREATE TABLE IF NOT EXISTS usuarios (
  id VARCHAR(36) PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  cpf VARCHAR(11) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ativo',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cartoes (
  id VARCHAR(36) PRIMARY KEY,
  numero VARCHAR(20) NOT NULL UNIQUE,
  usuario_id VARCHAR(36) NOT NULL,
  tipo VARCHAR(20) NOT NULL,
  saldo DECIMAL(8, 2) NOT NULL DEFAULT 0.00,
  status VARCHAR(20) NOT NULL DEFAULT 'ativo',
  theme_url VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS transacoes (
  id VARCHAR(36) PRIMARY KEY,
  cartao_id VARCHAR(36) NOT NULL,
  tipo VARCHAR(20) NOT NULL,
  valor DECIMAL(8, 2) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'confirmado',
  local_validador_id VARCHAR(50) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (cartao_id) REFERENCES cartoes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS validadores (
  id VARCHAR(50) PRIMARY KEY,
  status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);
